"""Type stubs for ReactFlowGraph."""

from typing import Any, Dict, List, Optional, Set
from transitions.extensions.diagrams_base import BaseGraph


class ReactFlowGraph(BaseGraph):
    def generate(self) -> None: ...

    def get_graph(
        self, title: Optional[str] = ..., roi_state: Optional[str] = ...
    ) -> Dict[str, List[Dict[str, Any]]]: ...

    def _build_edges(
        self, transitions: List[Dict[str, Any]]
    ) -> List[Dict[str, Any]]: ...

    def _get_used_state_ids(self, edges: List[Dict[str, Any]]) -> Set[str]: ...

    def _build_nodes(
        self, states: List[Dict[str, Any]], used_state_ids: Set[str]
    ) -> List[Dict[str, Any]]: ...

    def set_previous_transition(self, src: str, dst: str) -> None: ...

    def set_node_style(self, state: str, style: str) -> None: ...

    def reset_styling(self) -> None: ...
